### ISSUE TITLE
`npm dist-tag` fails on scoped packages

### ISSUE THREAD

**Issue by philwhln** [dickeyxxx/npm-register#71]
Is this because the `/` is being covered to `%2f`?

Similar issues with `npm dist-tag ls`.

```
phil@pro ~/s/o/api-js-client> npm dist-tag add @otono/ajax@0.0.17 beta
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "dist-tag" "add" "@otono/ajax@0.0.17" "beta"
npm ERR! node v6.9.0
npm ERR! npm  v4.0.3
npm ERR! code E500

npm ERR! server error : -/package/@otono%2fajax/dist-tags
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/phil/src/otono/api-js-client/npm-debug.log
```

```
logging error with Opbeat: { uuid: '82215b91-8265-4539-b625-4eaaac7520d4' }
TypeError: Cannot read property 'dist-tags' of undefined
    at Object.<anonymous> (/srv/npm-register/routes/dist_tags.js:17:20)
    at next (native)
    at Object.next (/srv/npm-register/node_modules/koa-timeout/node_modules/co/index.js:74:21)
    at /srv/npm-register/node_modules/koa-timeout/node_modules/co/index.js:93:18
    at /srv/npm-register/node_modules/koa-timeout/node_modules/co/index.js:224:7
    at tryCatcher (/srv/npm-register/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/srv/npm-register/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/srv/npm-register/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/srv/npm-register/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/srv/npm-register/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/srv/npm-register/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/srv/npm-register/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/srv/npm-register/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

  TypeError: Cannot read property 'dist-tags' of undefined
      at Object.<anonymous> (/srv/npm-register/routes/dist_tags.js:17:20)
      at next (native)
      at Object.next (/srv/npm-register/node_modules/koa-timeout/node_modules/co/index.js:74:21)
      at /srv/npm-register/node_modules/koa-timeout/node_modules/co/index.js:93:18
      at /srv/npm-register/node_modules/koa-timeout/node_modules/co/index.js:224:7
      at tryCatcher (/srv/npm-register/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/srv/npm-register/node_modules/bluebird/js/release/promise.js:504:31)
      at Promise._settlePromise (/srv/npm-register/node_modules/bluebird/js/release/promise.js:561:18)
      at Promise._settlePromise0 (/srv/npm-register/node_modules/bluebird/js/release/promise.js:606:10)
      at Promise._settlePromises (/srv/npm-register/node_modules/bluebird/js/release/promise.js:685:18)
      at Async._drainQueue (/srv/npm-register/node_modules/bluebird/js/release/async.js:138:16)
      at Async._drainQueues (/srv/npm-register/node_modules/bluebird/js/release/async.js:148:10)
      at Immediate.Async.drainQueues (/srv/npm-register/node_modules/bluebird/js/release/async.js:17:14)
      at runCallback (timers.js:574:20)
      at tryOnImmediate (timers.js:554:5)
      at processImmediate [as _immediateCallback] (timers.js:533:5)

measure#request=2634ms method=GET user-agent="npm/4.0.3 node/v6.9.0 darwin x64" status=500 path=/-/package/@otono%2fajax/dist-tags request_id=0.42078417696968606
```

**Comment by philwhln** [comment]
Turns out I had the wrong S3 creds, which isn't handled in a way that really gives any indication of this. Will try and PR some updates to handle this better.
