### ISSUE TITLE
Python >= v2.5.0 & < 3.0.0 is required

### ISSUE THREAD

**Issue by peteroreil** [dickeyxxx/npm-register#79]
Readme fails to identify Python is required as a dependency

**Comment by dickeyxxx** [comment]
what requires it?

**Comment by peteroreil** [comment]
Apologies. I should have appended the log.
Its a node-gyp dependency

```
user@host:~$ npm install npm-register
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead

> bcrypt@0.8.7 install /home/ubuntu/node_modules/bcrypt
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (/home/ubuntu/.nvm/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:401:14)
gyp ERR! stack     at /home/ubuntu/.nvm/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:330:11
gyp ERR! stack     at F (/home/ubuntu/.nvm/v6.0.0/lib/node_modules/npm/node_modules/which/which.js:63:16)
gyp ERR! stack     at E (/home/ubuntu/.nvm/v6.0.0/lib/node_modules/npm/node_modules/which/which.js:72:29)
gyp ERR! stack     at /home/ubuntu/.nvm/v6.0.0/lib/node_modules/npm/node_modules/which/which.js:81:16
gyp ERR! stack     at /home/ubuntu/.nvm/v6.0.0/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /home/ubuntu/.nvm/v6.0.0/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Linux 4.4.0-1020-aws
gyp ERR! command "/home/ubuntu/.nvm/v6.0.0/bin/node" "/home/ubuntu/.nvm/v6.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/node_modules/bcrypt
gyp ERR! node -v v6.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
```

Python is installed on this machine, but node-gyp does not support the installed version (required version.


I would think that it would be best to list installation dependencies and setup /configuration dependencies
in the README.

**Comment by dickeyxxx** [comment]
It's totally possible that if you use a later version of npm it may need a
different version of python. I'd like to stay out of attempting to list
dependencies like this since node-gyp isn't even a dependency of this
project, it's already on your machine. These dependencies will change and
the information will be out of date. Better to be lacking information than
providing misinformation.
